Repository sundayTen/pokr-server, pull requests merged in 2023-01, with the labels that each got.

#36 feat: reviews CRUD dummy API
  pokr-server/api/reviews/api.py
  pokr-server/db/models/__init__.py
  pokr-server/schemas/requests/review_request.py
  pokr-server/schemas/responses/common_response.py
  pokr-server/schemas/responses/review_response.py
Labels: 기능추가😆

#37 feat: add models(keyresult, initiative, memo)
  pokr-server/db/models/initiative.py
  pokr-server/db/models/keyresult.py
  pokr-server/db/models/memo.py
Labels: 기능추가😆

#38 chore: library versions update
  pokr-server/requirements.txt
Labels: 환경설정⚙

#44 feat: template Dummy API
  pokr-server/.gitignore
  pokr-server/api/templates/api.py
  pokr-server/main.py
  pokr-server/schemas/requests/template_request.py
  pokr-server/schemas/responses/template_response.py
Labels: 기능추가😆

#47 lighthouse ci 추가
  .github/workflows/lighthouse.yaml
  pokr-web/.github/workflows/lighthouse.yaml
  pokr-web/.lighthouserc.js
  pokr-web/hooks/useIsMobile.ts
Labels: 기능추가😆

#49 fix: dashboard 구조 추가
  pokr-web/.pnp.cjs
  pokr-web/.pnp.loader.mjs
  pokr-web/.vscode/settings.json
  pokr-web/.yarn/cache/@yarnpkg-esbuild-plugin-pnp-npm-3.0.0-rc.15-b916c218b3-04da15355a.zip
  pokr-web/.yarn/cache/cypress-npm-11.1.0-cfbafae592-ee0097778c.zip
  pokr-web/.yarn/cache/cypress-npm-12.3.0-957753b3a4-00658996bc.zip
  pokr-web/.yarn/cache/eslint-plugin-cypress-npm-2.12.1-6681f582fa-1f1c36e149.zip
  pokr-web/.yarn/cache/fsevents-patch-2882183fbf-8.zip
  pokr-web/.yarn/cache/globals-npm-11.12.0-1fa7f41a6c-67051a45ec.zip
  pokr-web/.yarn/cache/resolve-patch-0c52e0e4f7-5656f4d0be.zip
  pokr-web/.yarn/cache/resolve-patch-34cda421ec-4bf9f4f8a4.zip
  pokr-web/.yarn/releases/yarn-3.2.4.cjs
  pokr-web/.yarn/releases/yarn-3.3.1.cjs
  pokr-web/.yarnrc.yml
  pokr-web/app/dashboard/head.tsx
  pokr-web/app/dashboard/layout.tsx
  pokr-web/app/dashboard/page.tsx
  pokr-web/cypress.config.ts
  pokr-web/cypress/tsconfig.json
  pokr-web/next.config.js
  pokr-web/package.json
  pokr-web/yarn.lock
Labels: 리팩토링 🤨

#50 feat: 디바이스 환경 구분 유틸 추가
  pokr-web/app/layout.tsx
  pokr-web/components/common/Button/index.tsx
  pokr-web/hooks/useIsMobile.ts
  pokr-web/utils/device.ts
Labels: 기능추가😆

#55 ci test
  .github/test.js
  .github/workflows/lighthouse.yaml
Labels: 기능추가😆

#46 feat: jwt logic & jwt dummy api
  pokr-server/api/index.py
  pokr-server/crud/user/read.py
  pokr-server/env.py
  pokr-server/errors.py
  pokr-server/jwt.py
  pokr-server/schemas/common.py
Labels: 기능추가😆

#61 feat: my dashboard dummy api
  pokr-server/api/index.py
  pokr-server/api/me/api.py
  pokr-server/main.py
Labels: 기능추가😆
